version: '3'
services:
  mongodb:
    image: mongo:4.4.5
    mem_limit: 2gb
    mem_reservation: 1gb
    cpus: 0.5
    ports:
      - 27017:27017
    networks:
      - backend

  mongo_seed:
    image: mongo:4.4.5
    depends_on:
      - mongodb
    volumes:
      - ./database:/database
    command:
      /database/load_data.sh
    networks:
      - backend


  api:
    build:
      context: ./app
    ports:
     - 5000:5000
    depends_on:
      - mongodb
    networks:
      - backend

networks:
  backend:
